# Site settings
title: CorujaLab
email: rodrigo.avila@corujalab.com.br
url: https://corujalab.com.br
description: "Precisa de ajuda para organizar seu trabalho? Estamos à disposição!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 91aa9d #80B3FF
  secondary: 3e606f #FD6E8A
  secondary-dark: 193441 #A2122F

# Footer settings
footer:
  copyright: CorujaLab
  location: Onde Estamos
  social: Redes Sociais

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CorujaLab
  - title: facebook
    url: https://business.facebook.com/CorujaLab
  - title: github
    url: https://github.com/CorujaLab

# Postal address (add as many lines as necessary)
address:
  - line: Rua 3, nro. 65, Bairro Bela Vista
  - line: Montenegro, RS, 95780-000

# Build settings
markdown: kramdown
permalink: pretty
